### ISSUE TITLE
Feature form: data often not found issue

### ISSUE THREAD

**Issue by meierrom** [qwc-services/qwc-data-service#18]
Hi folks,

I had a closer look at feature forms in qwc-data-service.

Basically it's working just fine.

I click the feature form icon in the browser and then click the feature in the map. The feature in the map is nicely shown as being selected. However, often the form remains empty:

![Screenshot_2023-02-15_08-48-45](https://user-images.githubusercontent.com/35899323/218978767-96e52a5c-7444-4720-8713-c84751de7f3b.png)

I'm not sure but it may be some kind of conflict between two services, qwc-map-viewer and qwc-data-service. If I click the feature in the map and qwc-map-viewer logs the interaction, then the data in the form is nicely shown. The log looks like this:

qwc-map-viewer_1               | [pid: 7|app: 0|req: 47/47] 172.26.0.17 () {46 vars in 1679 bytes} [Wed Feb 15 08:38:56 2023] GET /assets/forms/autogen/qwc_demo_edit_points.ui?v=1676377393&lang=en-US => generated 2711 bytes in 2 msecs (HTTP/1.0 200) 2 headers in 80 bytes (1 switches on core 3)

On the other hand, if I click the feature and qwc-data-service logs the interaction, then the data in the form is missing showing "Querying". The log looks like this:

qwc-data-service_1             | [pid: 7|app: 0|req: 140/140] 172.26.0.17 () {46 vars in 1786 bytes} [Wed Feb 15 08:38:56 2023] GET /api/v1/data/qwc_demo.edit_polygons/?bbox=950754.4682685481,6003943.019006638,950765.0516018814,6003953.602339972&crs=EPSG:3857 => generated 125 bytes in 6 msecs (HTTP/1.0 200) 2 headers in 72 bytes (1 switches on core 2)

Any ideas, what is happening here?

Kind regards,
Roman

**Comment by meierrom** [comment]
Hi Sandro,

 I'm currently testing all features and it's quite fun to discover how far qwc2 has reached. However, the learning curve is rather steep for anybody new to this project I guess. To share issues and solutions should help in this regard I hope. Just like you I look forward to be able to contribute back.

Kind regards,
Roman

**Comment by manisandro** [comment]
I appreciate this, but issues like this one are inevitably linked to a user specific setup issue, which might be addressed by adjusting the configuration, or might also have revealed a genuine bug in one of the components, however determining what is going on requires a concrete debugging effort on the target setup, which the community cannot generally provide.

**Comment by meierrom** [comment]
Hi Sandro,

You were perfectly right! I somehow messed up things in my configuration. I'm yet to find out, what happened or if it's a bug. I'll report back as soon as I know more.

I did a fresh installation of all docker images.

By default the feature form tool wasn't accessible. It can however easily be added by adding some configuration in mapViewerConfig.json, so that the tool is shown in the menu and toolbar.

[...]
        "name": "TopBar",
        "cfg": {
          "menuItems": [
[...]
              {"key": "Editing", "icon": "editing"},
              {"key": "FeatureForm", "icon": "featureform"},
              {"key": "DxfExport", "icon": "dxfexport"},
[...]
          "toolbarItems": [
[...]
            {"key": "Identify", "icon": "identify_region", "mode": "Region"},
            {"key": "FeatureForm", "icon": "featureform"},
            {"key": "TimeManager", "icon": "clock"}
[...]
      {
        "name": "Editing"
      },
      {
          "name": "FeatureForm"
      },
      {
        "name": "MapCompare"
      },
[...]

![Screenshot_2023-02-16_10-53-44](https://user-images.githubusercontent.com/35899323/219345798-50e7cebd-d4aa-4ff2-b9f4-0f5954ca90aa.png)

![Screenshot_2023-02-16_10-53-59](https://user-images.githubusercontent.com/35899323/219345838-dcb15672-707e-49d1-99dc-038cb476a96f.png)

The issue I was facing earlier is no longer showing. It works just fine.

![Screenshot_2023-02-16_10-54-17](https://user-images.githubusercontent.com/35899323/219345913-e55de0d9-d1ff-4f36-9799-d59540d458fb.png)

Thanks for your valuable input!

Kind regards,
Roman

**Comment by tpo** [comment]
@meierrom in case the [official documentation](https://qwc-services.github.io/) is lacking then please feel welcome to improve it. Find the page that would fit best, click on "Edit this page" on the top right and submit a pull request.
