### ISSUE TITLE
How to delete a node?

### ISSUE THREAD

**Issue by meierrom** [qwc-services/qwc-data-service#22]
Hi folks,

I'm able to easily add nodes to polylines and polygons.

But how about deleting a node?

Kind regards,
Roman

**Comment by benoitblanc** [comment]
Hi @meierrom 

You can delete node with `SHIFT + click`

**Comment by tpo** [comment]
Documented that feature: https://github.com/qwc-services/qwc-services.github.io/commit/f8dd4a4cdda9e795fe129607d5017ac4ea82a993

**Comment by tpo** [comment]
@meierrom 

> Do I assume correctly that since this requires using a keyboard that there's no way to use this functionality on a smartphone or tablet?

Yes this currently can't be done on a touch screen.

AFAI can see this issue is resolved and I'm closing it.
